import type { Metadata } from "next";
import localFont from "next/font/local";
import SideBar from "@/components/SideBar";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Googlelogin from "@/components/GoogleLogin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="flex w-screen  gap-6 bg-black">
          <div className="w-[22%] py-4 flex justify-end bg-black">
            <SideBar />
          </div>
          <div className="w-[1050px] flex gap-4">
            <div className="w-[60%] bg-black">{children}</div>
            <div className="w-[35%] p-2 bg-black">
              <Googlelogin />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
