import type { Metadata } from "next";
import localFont from "next/font/local";
import SideBar from "@/components/SideBar";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Googlelogin from "@/components/GoogleLogin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="flex w-screen  lg:gap-6 gap-2 bg-black">
          <div className="lg:w-[25%] py-4 flex justify-end w-[15%] bg-black">
            <SideBar />
          </div>
          <div className="lg:w-[1050px] w-[85%] flex lg:gap-4 gap-2">
            <div className="lg:w-[55%] mr-10 md:mr-0 md:w-[65%] w-full bg-black">{children}</div>
            <div className="lg:w-[35%] sm:w-[35%] md:block hidden  p-2 bg-black">
              <Googlelogin />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
