import type { Metadata } from "next";
import localFont from "next/font/local";
import SideBar from "@/components/SideBar";
import { GoogleOAuthProvider } from "@react-oauth/google";
import Googlelogin from "@/components/GoogleLogin";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body>
        <div className="flex w-screen h-screen gap-4">
          <div className="w-[22%] py-4 flex justify-end">
            <SideBar />
          </div>
          <div className="w-[1050px] flex gap-4">
            <div className="w-2/3 ">{children}</div>
            <div className="w-[30%]">
              <Googlelogin/>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
